---
- name: AIDE installation and configuration
  become: true
  block:
    - name: Debian family AIDE installation
      ansible.builtin.apt:
        name: aide-common
        state: present
        install_recommends: false
      when:
        - ansible_os_family == "Debian"

    - name: RedHat family AIDE package installation
      ansible.builtin.dnf:
        name: aide
        state: present
      when:
        - ansible_os_family == "RedHat"

    - name: Stat AIDE cron.daily
      ansible.builtin.stat:
        path: /etc/cron.daily/aide
      register: aidecron

    - name: Install AIDE service
      ansible.builtin.template:
        src: lib/systemd/system/aidecheck.service.j2
        dest: /lib/systemd/system/aidecheck.service
        backup: true
        mode: "0644"
        owner: root
        group: root
      when:
        - not aidecron.stat.exists

    - name: Install AIDE timer
      ansible.builtin.template:
        src: lib/systemd/system/aidecheck.timer.j2
        dest: /lib/systemd/system/aidecheck.timer
        backup: true
        mode: "0644"
        owner: root
        group: root
      when:
        - not aidecron.stat.exists
      notify:
        - Reload systemd
        - Enable aidecheck

    - name: Configure AIDE checksums
      ansible.builtin.lineinfile:
        path: "{{ '/etc/aide/aide.conf' if ansible_os_family == 'Debian' else '/etc/aide.conf' }}"
        state: present
        regexp: ^Checksums =
        line: Checksums = {{ aide_checksums }}
        mode: "0640"
        create: false
        validate: aide --config-check --config=%s

    - name: Get AIDE include config
      ansible.builtin.command:
        cmd: grep -m1 -E "^@@(x_include|include) \/" "{{ '/etc/aide/aide.conf' if ansible_os_family == 'Debian' else '/etc/aide.conf' }}"
      register: grep_aide_include
      changed_when: false
      failed_when: false
      check_mode: false

    - name: Set AIDE include directory as fact
      ansible.builtin.set_fact:
        aide_include_d: "{{ 'false' if grep_aide_include.rc != 0 else grep_aide_include.stdout.split()[1] }}"

    - name: Check if AIDE include directory exits
      ansible.builtin.stat:
        path: "{{ aide_include_d }}"
      register: aide_config_d

    - name: Add auditd tools
      ansible.builtin.lineinfile:
        path: "{{ '/etc/aide/aide.conf' if ansible_os_family == 'Debian' else '/etc/aide.conf' }}"
        state: "{{ 'absent' if aide_config_d.stat.exists else 'present' }}"
        regexp: ^[# ]*{{ item }}
        line: "{{ item }} p+i+n+u+g+s+b+acl+xattrs+sha512"
        mode: "0640"
        owner: root
        group: root
        create: false
        validate: aide --config-check --config=%s
      loop:
        - /usr/sbin/auditctl
        - /usr/sbin/auditd
        - /usr/sbin/ausearch
        - /usr/sbin/aureport
        - /usr/sbin/autrace
        - /usr/sbin/augenrules
        - /usr/sbin/audispd
      when:
        - not aide_config_d.stat.exists

    - name: Add AIDE dir exclusions
      ansible.builtin.lineinfile:
        path: "{{ '/etc/aide/aide.conf' if ansible_os_family == 'Debian' else '/etc/aide.conf' }}"
        line: "!{{ item }}"
        state: "{{ 'absent' if aide_config_d.stat.exists else 'present' }}"
        mode: "0640"
        owner: root
        group: root
        create: false
        validate: aide --config-check --config=%s
      with_items:
        - "{{ aide_dir_exclusions }}"
      when:
        - not aide_config_d.stat.exists

    - name: Add auditd tools in include directory
      ansible.builtin.lineinfile:
        path: "{{ aide_include_d }}/99_aide_auditd"
        state: present
        line: "{{ item }} p+i+n+u+g+s+b+acl+xattrs+sha512"
        mode: "0640"
        owner: root
        group: root
        create: true
        validate: aide --config-check --config=%s
      loop:
        - /usr/sbin/auditctl
        - /usr/sbin/auditd
        - /usr/sbin/ausearch
        - /usr/sbin/aureport
        - /usr/sbin/autrace
        - /usr/sbin/augenrules
        - /usr/sbin/audispd
      when:
        - aide_config_d.stat.exists

    - name: Add AIDE dir exclusions
      ansible.builtin.lineinfile:
        path: "{{ aide_include_d }}/99_aide_exclusions"
        line: "!{{ item }}"
        state: present
        mode: "0640"
        owner: root
        group: root
        create: true
        validate: aide --config-check --config=%s
      with_items:
        - "{{ aide_dir_exclusions }}"
      when:
        - aide_config_d.stat.exists

    - name: Stat Debian aide.db
      ansible.builtin.stat:
        path: /var/lib/aide/aide.db
      register: ubuaidedb
      when:
        - ansible_os_family == "Debian"

    - name: Stat RedHat aide.db
      ansible.builtin.stat:
        path: /var/lib/aide/aide.db.gz
      register: rhelaidedb
      changed_when: false
      failed_when: false
      when:
        - ansible_os_family == "RedHat"

    - name: Initialize RedHat AIDE
      ansible.builtin.command:
        cmd: aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
      register: init_redhat_aide
      changed_when: init_redhat_aide.rc != 0
      failed_when: init_redhat_aide.rc != 0
      when:
        - ansible_os_family == "RedHat"
        - not rhelaidedb.stat.exists

    - name: Stat RedHat aide.db.new.gz
      ansible.builtin.stat:
        path: /var/lib/aide/aide.db.new.gz
      register: rhelaidedbnew
      changed_when: false
      failed_when: false
      when:
        - ansible_os_family == "RedHat"

    - name: Copy RedHat AIDE database
      ansible.builtin.command:
        cmd: cp /var/lib/aide/aide.db.gz /var/lib/aide/aide.db.new.gz
      register: cp_redhat_aide_db
      changed_when: cp_redhat_aide_db.rc != 0
      failed_when: cp_redhat_aide_db.rc != 0
      when:
        - ansible_os_family == "RedHat"
        - not rhelaidedbnew.stat.exists

    - name: Initialize Debian AIDE
      ansible.builtin.command:
        cmd: aideinit --force --yes
      register: init_debian_aide
      changed_when: init_debian_aide.rc != 0
      failed_when: init_debian_aide.rc != 0
      when:
        - ansible_os_family == "Debian"
        - not ubuaidedb.stat.exists
