---
- name: Disable systemd ctrl-alt-del
  become: true
  ansible.builtin.systemd:
    name: ctrl-alt-del.target
    masked: true
    enabled: false
    state: stopped
  when:
    - not ansible_os_family == "RedHat"

- name: Disable systemd ctrl-alt-del - RedHat family
  become: true
  ansible.builtin.systemd:
    name: ctrl-alt-del.target
    masked: true
    enabled: false
    state: stopped
  changed_when: false
  when:
    - ansible_os_family == "RedHat"
