---
- name: Remove /tmp from fstab
  become: true
  ansible.posix.mount:
    path: /tmp
    state: absent

- name: Remove floppy from fstab
  become: true
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: absent
    regexp: ^(.*)floppy(.*)$
