---
- name: Ensure kmod is installed
  become: true
  ansible.builtin.package:
    name: kmod
    state: present
  tags:
    - modprobe

- name: Blacklist kernel file system modules
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/modprobe.d/disablefs.conf
    line: blacklist {{ item }}
    mode: "0644"
    owner: root
    group: root
    state: present
    create: true
  with_items:
    - "{{ fs_modules_blocklist }}"
  tags:
    - modprobe
    - CCE-80835-2
    - CCE-81031-7
    - CIS-UBUNTU2004-1.1.1.1
    - CIS-UBUNTU2004-1.1.1.2
    - CIS-UBUNTU2004-1.1.1.3
    - CIS-UBUNTU2004-1.1.1.4
    - CIS-UBUNTU2004-1.1.1.5
    - CIS-UBUNTU2004-1.1.1.5
    - CIS-UBUNTU2004-1.1.1.6
    - CIS-UBUNTU2004-1.1.1.7
    - M1038
    - M1042

- name: Blacklist kernel network modules
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/modprobe.d/disablenet.conf
    line: blacklist {{ item }}
    mode: "0644"
    owner: root
    group: root
    state: present
    create: true
  with_items:
    - "{{ net_modules_blocklist }}"
  tags:
    - modprobe
    - CCE-80834-5
    - CCE-82028-2
    - CCE-82297-3
    - CIS-UBUNTU2004-3.4.1
    - CIS-UBUNTU2004-3.4.2
    - CIS-UBUNTU2004-3.4.3
    - CIS-UBUNTU2004-3.4.4
    - M1038
    - M1042

- name: Allow USB kernel modules if USBGuard is used
  ansible.builtin.set_fact:
    misc_modules_usbguard: "{{ misc_modules_blocklist | reject('search', 'usb') | list }}"

- name: Blacklist misc kernel modules
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/modprobe.d/disablemod.conf
    line: blacklist {{ item }}
    mode: "0644"
    owner: root
    group: root
    state: present
    create: true
  with_items:
    - "{{ misc_modules_usbguard if manage_usbguard else misc_modules_blocklist }}"
  tags:
    - modprobe
    - CCE-80832-9
    - CCE-82005-0
    - CCE-82059-7
    - CIS-UBUNTU2004-1.1.24
    - M1034
    - M1038
    - M1042

- name: Stat blacklisted kernel modules
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      /usr/sbin/modprobe -c | grep -o '^blacklist .*' | awk '{print $2}'
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: modprobe_blacklist.rc != 0
  register: modprobe_blacklist
  tags:
    - modprobe
    - M1034
    - M1038
    - M1042

- name: Block blacklisted kernel modules
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/modprobe.d/blacklist-blocked.conf
    line: install {{ item }} /bin/true
    mode: "0644"
    owner: root
    group: root
    state: present
    create: true
  with_items:
    - "{{ modprobe_blacklist.stdout_lines | sort | unique }}"
  tags:
    - modprobe
    - M1034
    - M1038
    - M1042
