---
- name: Merge all DNS servers
  ansible.builtin.set_fact:
    dns_merged: "{{ dns + fallback_dns }}"

- name: Configure systemd resolved
  become: true
  ansible.builtin.template:
    src: "{{ resolved_conf_template }}"
    dest: /etc/systemd/resolved.conf
    backup: true
    mode: "0644"
    owner: root
    group: root
  register: resolved_conf

- name: Ensure configuration is active
  become: true
  when:
    - ansible_virtualization_type not in ["container", "docker", "podman"]
    - resolved_conf is changed
  block:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Restart resolved service
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
      register: resolved_service
      failed_when:
        - resolved_service is not success
        - not 'Could not find the requested service' in resolved_service.msg
