---
- name: Merge all DNS servers
  ansible.builtin.set_fact:
    dns_merged: "{{ dns + fallback_dns }}"

- name: Configure systemd resolved
  become: true
  ansible.builtin.template:
    src: "{{ resolved_conf_template }}"
    dest: /etc/systemd/resolved.conf
    backup: true
    mode: "0644"
    owner: root
    group: root
  notify:
    - Reload systemd
  tags:
    - resolved
    - systemd
    - CCE-84049-6

- name: Add nameservers to resolv.conf
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/resolv.conf
    line: nameserver {{ item }}
    mode: "0644"
    owner: root
    group: root
    state: present
  loop: "{{ dns_merged | sort | unique }}"
  when:
    - ansible_os_family == "RedHat"
  tags:
    - resolved
