---
- name: Ensure sysctl configuration dir has the correct permissions
  become: true
  ansible.builtin.file:
    path: "{{ sysctl_conf_dir }}"
    mode: "0755"
    owner: root
    group: root
    state: directory

- name: Ensure old sysctl file is removed
  become: true
  ansible.builtin.file:
    path: "{{ sysctl_conf_dir }}/zz-hardening.conf"
    state: absent

- name: Template the sysctl file with general sysctl hardening settings
  become: true
  ansible.builtin.template:
    src: "{{ sysctl_main_config_template }}"
    dest: "{{ sysctl_conf_dir }}/zz-main-hardening.conf"
    mode: "0644"
    owner: root
    group: root
    backup: false
  notify:
    - Restart sysctl

- name: Template sysctl file with IPv6 settings
  become: true
  ansible.builtin.template:
    src: "{{ sysctl_ipv6_config_template }}"
    dest: "{{ sysctl_conf_dir }}/zz-ipv6-hardening.conf"
    mode: "0644"
    owner: root
    group: root
    backup: false
  when:
    - system_has_ipv6
    - not disable_ipv6
  notify:
    - Restart sysctl
