---
- name: Ensure sysctl configuration dir has the correct permissions
  become: true
  ansible.builtin.file:
    path: "{{ sysctl_conf_dir }}"
    mode: "0755"
    owner: root
    group: root
    state: directory

- name: Ensure old sysctl file is removed
  become: true
  ansible.builtin.file:
    path: "{{ sysctl_conf_dir }}/zz-hardening.conf"
    state: absent

- name: Template the sysctl file with general sysctl hardening settings
  become: true
  ansible.builtin.template:
    src: "{{ sysctl_main_config_template }}"
    dest: "{{ sysctl_conf_dir }}/zz-main-hardening.conf"
    mode: "0644"
    owner: root
    group: root
    backup: false
  notify:
    - Restart sysctl
  tags:
    - sysctl
    - CCE-80913-7
    - CCE-80915-2
    - CCE-80916-0
    - CCE-80917-8
    - CCE-80918-6
    - CCE-80919-4
    - CCE-80920-2
    - CCE-80921-0
    - CCE-80922-8
    - CCE-80953-3
    - CCE-81006-9
    - CCE-81007-7
    - CCE-81009-3
    - CCE-81010-1
    - CCE-81011-9
    - CCE-81013-5
    - CCE-81021-8
    - CCE-81024-2
    - CCE-81027-5
    - CCE-81030-9
    - CCE-81054-9
    - CCE-82974-7
    - CIS-UBUNTU2004-1.5.2
    - CIS-UBUNTU2004-1.5.4
    - CIS-UBUNTU2004-3.2.1
    - CIS-UBUNTU2004-3.2.2
    - CIS-UBUNTU2004-3.3.1
    - CIS-UBUNTU2004-3.3.2
    - CIS-UBUNTU2004-3.3.3
    - CIS-UBUNTU2004-3.3.4
    - CIS-UBUNTU2004-3.3.5
    - CIS-UBUNTU2004-3.3.6
    - CIS-UBUNTU2004-3.3.7
    - CIS-UBUNTU2004-3.3.8
    - CIS-UBUNTU2004-3.3.9
    - UBTU-20-010412
    - UBTU-20-010448

- name: Template sysctl file with IPv6 settings
  become: true
  ansible.builtin.template:
    src: "{{ sysctl_ipv6_config_template }}"
    dest: "{{ sysctl_conf_dir }}/zz-ipv6-hardening.conf"
    mode: "0644"
    owner: root
    group: root
    backup: false
  when:
    - system_has_ipv6
    - not disable_ipv6
  notify:
    - Restart sysctl
  tags:
    - ipv6
