---
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  log: true
  inventory:
    host_vars:
      almalinux8:
        disable_wireless: true
        manage_compilers: false
        manage_timesyncd: false
        sshd_admin_net:
          - "0.0.0.0/0"
        sshd_allow_groups:
          - vagrant
          - sudo
        sshd_host_keys_group: ssh_keys
        sshd_update_moduli: true
        suid_sgid_permissions: false
      almalinux9:
        manage_resolved: false
        manage_timesyncd: false
        sshd_admin_net:
          - "0.0.0.0/0"
        sshd_allow_groups:
          - vagrant
          - sudo
        sshd_host_keys_group: ssh_keys
        sshd_update_moduli: true
        sysctl_conf_dir: /etc/sysctl.d/
        system_upgrade: false
        ufw_rate_limit: true
      bookworm:
        ansible_become_pass: vagrant
        ansible_python_interpreter: /usr/bin/python3
        disable_wireless: false
        manage_usbguard: false
        rkhunter_web_cmd: wget
        sshd_admin_net:
          - "0.0.0.0/0"
        sshd_allow_groups:
          - vagrant
          - sudo
        sshd_update_moduli: true
        system_upgrade: false
      focal:
        disable_wireless: true
        sshd_admin_net:
          - "0.0.0.0/0"
        sshd_allow_groups:
          - vagrant
          - sudo
        sshd_update_moduli: true
        suid_sgid_permissions: false
        sysctl_conf_dir: /etc/sysctl.d/
        umask_value: "027"
        ufw_rate_limit: true
      jammy:
        disable_ipv6: true
        disable_wireless: true
        sshd_admin_net:
          - "0.0.0.0/0"
        sshd_allow_groups:
          - vagrant
          - sudo
        suid_sgid_permissions: false
        sshd_match_users:
          - user: testuser01
            rules:
              - AllowUsers testuser01
              - AuthenticationMethods password
              - PasswordAuthentication yes
          - user: testuser02
            rules:
              - AllowUsers testuser02
              - Banner none
platforms:
  - name: almalinux8
    box: almalinux/8
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 2048
  - name: almalinux9
    box: almalinux/9
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 2048
  - name: bookworm
    box: debian/bookworm64
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
  - name: focal
    box: bento/ubuntu-20.04
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - "vbguest.installer_options = { allow_kernel_upgrade: true }"
    memory: 1024
  - name: jammy
    box: ubuntu/jammy64
    config_options:
      vm.boot_timeout: 600
      synced_folder: false
    provider_raw_config_args:
      - customize ['modifyvm', :id, '--uart1', '0x3F8', '4']
      - customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]
    instance_raw_config_args:
      - "vbguest.installer_options = { allow_kernel_upgrade: true }"
    memory: 1024
verifier:
  name: ansible
scenario:
  name: default
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
