---
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  log: true
  inventory:
    host_vars:
      noble:
        automatic_updates:
          enabled: true
          only_security: true
          reboot: true
          reboot_from_time: "2:00"
          reboot_time_margin_mins: 1
          custom_origins:
            - "Docker:noble"
        kernel_lockdown: true
        sshd_admin_net:
          - 0.0.0.0/0
        sshd_allow_groups:
          - vagrant
          - sudo
        sshd_kex_algorithms:
          - "sntrup761x25519-sha512@openssh.com"
          - "curve25519-sha256@libssh.org"
          - "diffie-hellman-group16-sha512"
          - "diffie-hellman-group18-sha512"
          - "ecdh-sha2-nistp521"
        sshd_update_moduli: true
        sshd_match_users:
          - user: testuser01
            rules:
              - AllowUsers testuser01
              - AuthenticationMethods password
              - PasswordAuthentication yes
          - user: testuser02
            rules:
              - AllowUsers testuser02
              - Banner none
        ufw_rate_limit: true
platforms:
  - name: noble
    box: bento/ubuntu-24.04
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
verifier:
  name: ansible
scenario:
  name: single
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
